apiVersion: v1
kind: ConfigMap
metadata:
  name: laravel-config
data:
  APP_ENV: local
  APP_KEY: base64:YOUR_APP_KEY_HERE
  APP_DEBUG: 'true'
  APP_URL: http://localhost:8080
  DB_CONNECTION: mysql
  DB_HOST: mysql
  DB_PORT: '3306'
  DB_DATABASE: vandy-db
  DB_USERNAME: root
  DB_PASSWORD: Hello@123
  CACHE_DRIVER: file
  SESSION_DRIVER: file
  QUEUE_DRIVER: sync