apiVersion: v1
kind: Service
metadata:
  name: laravel-service
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
    - port: 22
      targetPort: 22
      protocol: TCP
  selector:
    app: laravel-app